"""Adiciona campo is_admin ao modelo User

Revision ID: 6109287873b7
Revises: 8c6ae1e597db
Create Date: 2025-05-19 21:49:55.708001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6109287873b7'
down_revision = '8c6ae1e597db'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Adiciona a coluna com valor padrão
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='FALSE'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
