"""Adiciona coluna is_active para controlar o status do usuário

Revision ID: 7c42a328ba5d
Revises: c76426d17851
Create Date: 2025-05-20 21:11:18.699939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c42a328ba5d'
down_revision = 'c76426d17851'
branch_labels = None
depends_on = None


def upgrade():
    # ### comandos auto-gerados pelo Alembic ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Adicionando a coluna is_active
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        
        # Alterando a coluna username para um tamanho menor
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        
        # Alterando a coluna password para TEXT, que não tem limite de tamanho
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),  # Ajuste conforme a necessidade
               type_=sa.Text(),  # Mudando para TEXT, que não tem tamanho fixo
               existing_nullable=False)
        
        # Alterando a coluna is_admin para permitir valores nulos
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### Fim dos comandos Alembic ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Revertendo alterações feitas na coluna is_admin
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        
        # Revertendo a alteração da coluna password para o tipo original VARCHAR(200)
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        
        # Revertendo a alteração da coluna username para o tamanho original (opcional)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        
        # Removendo a coluna is_active
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
