"""Adiciona cidade e uf ao User

Revision ID: ae6655ad5206
Revises: 9320ff1a0b39
Create Date: 2025-05-21 21:55:49.015769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6655ad5206'
down_revision = '9320ff1a0b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
